# Site settings
title: Simon's Blog
email: simon@simonlee.me
description: > # this means to ignore newlines until "baseurl:"
  This is about my adventures in life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simonlee.me" # the base hostname & protocol for your site
twitter_username: bestbananapie
github_username:  bestbananapie

# Build settings
markdown: kramdown
